apiVersion: apps/v1
kind: Deployment
metadata:
  name: log4shell-deploy1
  labels:
    app: log4shell-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log4shell-app1
  template:
    metadata:
      labels:
        app: log4shell-app1
        affected-by: cve-2021-44228
    spec:
      containers:
      - image: quay.io/swains/log4shell-vuln:latest
        imagePullPolicy: Always
        name: log4shell-app
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
